# Generated by Django 3.2 on 2021-04-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'publicação',
                'verbose_name_plural': 'publicações',
            },
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'termo de pesquisa',
                'verbose_name_plural': 'termos de pesquisa',
            },
        ),
    ]
