# Generated by Django 3.2 on 2021-04-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_publication_terms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='terms',
            new_name='types',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='data',
        ),
        migrations.AddField(
            model_name='publication',
            name='code',
            field=models.IntegerField(null=True, verbose_name='código do diário'),
        ),
        migrations.AddField(
            model_name='publication',
            name='content',
            field=models.TextField(null=True, verbose_name='conteúdo'),
        ),
        migrations.AddField(
            model_name='publication',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='data'),
        ),
        migrations.AddField(
            model_name='publication',
            name='observation',
            field=models.TextField(null=True, verbose_name='observação'),
        ),
        migrations.AlterField(
            model_name='searchterm',
            name='classification',
            field=models.CharField(max_length=60, verbose_name='classificação'),
        ),
        migrations.AlterField(
            model_name='searchterm',
            name='term',
            field=models.CharField(max_length=100, verbose_name='termo de pesquisa'),
        ),
    ]
